"""Response models for the read-only /projects browsing API (project list ->
drawings in a project -> extraction/comparison detail for one drawing)."""
from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, ConfigDict

from app.schemas.job import GadDxfRunOut
from app.schemas.jobcard import JobCardExtraction


class ProjectCreate(BaseModel):
    name: str
    so_no: Optional[str] = None
    description: Optional[str] = None


class ProjectListItem(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    so_no: Optional[str] = None
    name: str
    description: Optional[str] = None
    created_at: datetime
    updated_at: Optional[datetime] = None
    drawing_count: int


class DrawingListItem(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    title: str
    type: int
    type_label: str
    is_extracted: bool = False
    extraction_error: Optional[str] = None
    created_at: datetime
    updated_at: Optional[datetime] = None


class ProjectDetailResponse(ProjectListItem):
    drawings: list[DrawingListItem]


class ExtractionSpecItem(BaseModel):
    parameter: str
    value: str


class ExtractionBomItem(BaseModel):
    sr_no: str = ""
    description: str = ""
    qty: str = ""
    material: str = ""
    size: str = ""
    remarks: str = ""
    bom_table: str = ""


class ExtractionCalloutItem(BaseModel):
    label: str = ""
    category: str = ""


class ExtractionView(BaseModel):
    drawing_category: str = ""
    title_block: dict[str, str] = {}
    specifications: list[ExtractionSpecItem] = []
    bill_of_materials: list[ExtractionBomItem] = []
    dimensional_callouts: list[ExtractionCalloutItem] = []
    notes: list[str] = []


class ComparisonFindingItem(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    parameter: str
    gad_value: str
    subd_value: str
    status: str
    mismatch_acceptance: bool


class JobCardComparisonItem(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    parameter: str
    jobcard_value: str
    subd_value: str
    status: str
    mismatch_acceptance: bool


class JobCardComparisonGroup(BaseModel):
    """One job card <-> sub-drawing pair's findings. counterpart is the other
    side from the drawing being viewed: the sub-drawing when viewing a job
    card, the job card when viewing a sub-drawing."""

    counterpart: DrawingListItem
    findings: list[JobCardComparisonItem]


class DxfOutputItem(BaseModel):
    label: str
    image_url: str


class DrawingDetailResponse(BaseModel):
    id: int
    title: str
    type: int
    type_label: str
    is_extracted: bool = False
    extraction_error: Optional[str] = None
    created_at: datetime
    updated_at: Optional[datetime] = None
    extraction: Optional[ExtractionView] = None
    comparison: list[ComparisonFindingItem] = []
    # For SUB drawings only: the GAD drawing it was compared against.
    gad_drawing: Optional[DrawingListItem] = None
    # For JOB_CARD drawings only: extraction-only, no comparison, different shape.
    job_card_extraction: Optional[JobCardExtraction] = None
    # For JOB_CARD and SUB drawings: job card vs heating-element sub-drawing
    # comparisons, one group per counterpart drawing.
    jobcard_comparisons: list[JobCardComparisonGroup] = []
    # For DXF drawings (GAD DXF or cutting-sheet DXF): GAD vs DXF validation runs
    # the drawing took part in, newest first.
    gad_dxf_validations: list[GadDxfRunOut] = []
    # For DXF drawings only: the overlay PNGs generated by the split+overlay pipeline.
    dxf_outputs: list[DxfOutputItem] = []
